export const LOGIN_USER= 'LOGIN_USER';

export const REGISTER_USER = 'REGISTER_USER';

export const AUTH_USER = 'AUTH_USER';

export const LOGOUT_USER = 'LOGOUT_USER';

export const GET_PRODUCTS_BY_SELL = 'GET_PRODUCTS_BY_SELL';

export const GET_PRODUCTS_BY_ARRIVAL = 'GET_PRODUCT_BY_ARRIVAL';

export const GET_BRANDS = 'GET_BRANDS';

export const GET_WOODS = 'GET_WOODS';

export const GET_PRODUCTS_TO_SHOP = 'GET_PRODUCTS_TO_SHOP';

export const ADD_PRODUCT = 'ADD_PRODUCT';

export const CLEAR_PRODUCT = 'CLEAR_PRODUCT';

export const ADD_BRAND = 'ADD_BRAND';

export const ADD_WOOD = 'ADD_WOOD'

export const GET_POST_DETAIL = 'GET_POST_DETAIL'

export const CLEAR_PRODUCT_DETAIL = 'CLEAR_PRODUCT_DETAIL'

export const ADD_TO_CART = 'ADD_TO_CART';

//////////////////////////////////////////////////////

export const GET_TOP10_TAGS = 'GET_TOP10_TAGS';

export const GET_ALL_TAGS = 'GET_ALL_TAGS';

export const ADD_TAG = 'ADD_TAG';

export const LIKE_POST = 'LIKE_POST';

export const COMMENT_POST = 'COMMENT_POST';

export const GET_USER_TAG = 'GET_USER_TAG';

export const HIDE_POST = "HIDE_POST";

export const UPDATE_DETAIL = "UPDATE_DETAIL";

export const LIKE_DETAIL = "LIKE_DETAIL";

export const LIKE_COMMENT = "LIKE_COMMENT";

export const HIDE_POST_DETAIL = "HIDE_POST_DETAIL";

export const DELETE_POST = "DELETE_POST";

export const DELETE_COMMENT = "DELETE_COMMENT";

export const GET_POLICY = "GET_POLICY";

export const CLEAR_POST_DETAIL ="CLEAR_POST_DETAIL";

export const REPORT_POST = "REPORT_POST";

export const GET_STORY = "GET_STORY";

export const STORE_REGISTER_INFO = "STORE_REGISTER_INFO";

export const GET_TAG_POSTS = "GET_TAG_POSTS";

export const FOLLOW_TAG = "FOLLOW_TAG";

export const UN_FOLLOW_TAG = "UN_FOLLOW_TAG";

export const SEARCH_RESULT = "SEARCH_RESULT";

export const LOAD_MORE_USER = "LOAD_MORE_USER";

export const LOAD_MORE_TAG = "LOAD_MORE_TAG";

export const UPDATE_POST = "UPDATE_POST";

export const UPDATE_POST_DETAIL = "UPDATE_POST_DETAIL";

export const GET_ALL_REPORTS = "GET_ALL_REPORTS";

export const SORT_REPORT = "SORT_REPORT";

export const GET_REPORT_DETAIL = "GET_REPORT_DETAIL";

export const UPDATE_REPORT = "UPDATE_REPORT";
 
export const DELETE_POST_REPORT = "DELETE_POST_REPORT";

export const DELETE_COMMENT_REPORT = "DELETE_COMMENT_REPORT";


export const GET_ALL_ACCOUNT = "GET_ALL_ACCOUNT";

export const SORT_ACCOUNT = "SORT_ACCOUNT";

export const UPDATE_ACCOUNT = "UPDATE_ACCOUNT";

export const DELETE_ACCOUNT = "DELETE_ACCOUNT";

export const GET_ACCOUNT = "GET_ACCOUNT";

export const CLEAR = "CLEAR";

//////////////////////////////

export const GET_POST = 'GET_POST';
export const GET_TYPE = 'GET_TYPE';
export const SAVE_DETAIL = 'SAVE_DETAIL';
export const SAVE_POST = 'SAVE_POST';
export const UPDATE_IMG = 'UPDATE_IMG';
export const PROFILE_IMG = 'PROFILE_IMG';
export const UPDATE_PRO = 'UPDATE_PRO';
export const FOLLOW_USER = 'FOLLOW_USER';
// export const UNFOLLOW_USER = 'FOLLOW_USER';

export const CHANGE_USER = 'CHANGE_USER';
export const GET_CONVERSATION = 'GET_CONVERSATION';
export const GET_MESS = 'GET_MESS';
export const SEND_MESS = 'SEND_MESS';
export const SEEN_MESS = 'SEEN_MESS';

export const GET_NOTIFICATION = 'GET_NOTIFICATION';
export const NOTIFICATION_DETAIL = 'NOTIFICATION_DETAIL';
export const NOTIFICATION_SEENALL = 'NOTIFICATION_SEENALL';

export const UPLOAD_IMG = 'UPLOAD_IMG';
export const CHANGE_PRO = 'CHANGE_PRO';
export const CHANGE_IMG = 'CHANGE_IMG';


export const VIEW_STORY = "VIEW_STORY";
export const CREATE_STORY = "CREATE_STORY";
export const DELETE_STORY ="DELETE_STORY";
export const GET_HIGHLIGHT_STORY = "GET_HIGHLIGHT_STORY";
export const GET_ALL_STORY = "GET_ALL_STORY";
export const CREATE_HIGHLIGHT_STORY = "CREATE_HIGHLIGHT_STORY";
export const DELETE_HIGHLIGHT_STORY = "DELETE_HIGHLIGHT_STORY";
export const EDIT_HIGHLIGHT_STORY = "EDIT_HIGHLIGHT_STORY";
export const GET_RECOMMEND_POST = "GET_RECOMMEND_POST";
export const BLOCK_USER = "BLOCK_USER";

export const GET_BLOCKED_USERS = "GET_BLOCKED_USERS";
export const UNBLOCKED_USERS = "UNBLOCKED_USERS";

export const RESTRICT_USER = "RESTRICT_USER";
export const RESTRICTED = "RESTRICTED";
export const DELETE_RESTRICTED_FUNCTION = "DELETE_RESTRICTED_FUNCTION";

export const GET_GROWTH_OF_USER = "GET_GROWTH_OF_USER";
export const GET_PERCENTEAGE_OF_AGE = "GET_PERCENTEAGE_OF_AGE";
export const GET_NUM_OF_USERS = "GET_NUM_OF_USERS";
export const GET_UNUSED_USERS = "GET_UNUSED_USERS";
export const GET_NEW_USER = "GET_NEW_USER";
export const GET_TOTAL_OF_NEW_POSTS = "GET_TOTAL_OF_NEW_POSTS";
export const GET_TOP_TEN_USERS = "GET_TOP_TEN_USERS";
export const GET_USERS_NATIONALITIES = "GET_USERS_NATIONALITIES";
export const GET_USERS_BEHAVIORS = "GET_USERS_BEHAVIORS";
export const GET_NATIONALITY = "GET_NATIONALITY";


export const GET_GROUP = "GET_GROUP";
export const GET_GROUPMESS = "GET_GROUPMESS";
export const SEND_GROUP_MESS = "SEND_GROUP_MESS";
export const CREATE_GROUP = "CREATE_GROUP";
export const EDIT_TITLE = "EDIT_TITLE";
export const ADD_MEMBER = "ADD_MEMBER";
export const REMOVE_MEMBER = "REMOVE_MEMBER";
export const UPLOAD_GROUPIMG = "UPLOAD_GROUPIMG";
export const CHANGE_GROUPIMG = "CHANGE_GROUPIMG";
export const SEEN_GROUP = "SEEN_GROUP";
export const FIND_PERSONAL = "FIND_PERSONAL";
export const CHANGE_PRIVATE = "CHANGE_PRIVATE";
export const REQUEST_FOLLOW = "REQUEST_FOLLOW";
export const ACCEPT_FOLLOW = "ACCEPT_FOLLOW" ;
export const FIND_LOCATION = "FIND_LOCATION";
export const GET_ICESERVERS = "GET_ICESERVERS";